---
# Enable only the engines you need
engines:
  local:
    lvm:
      enabled: true
    zfs:
      enabled: false
    rawfile:
      enabled: false
  replicated:
    mayastor:
      enabled: false

localpv-provisioner:
  localpv:
    enabled: true
    basePath: /var/openebs/local
  hostpathClass:
    enabled: true
    name: openebs-hostpath
    isDefaultClass: true

loki:
  enabled: false

minio:
  enabled: false
