---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  prune: true
  interval: 10m
  path: ./clusters/building-blocks/base/namespaces/
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  prune: true
  interval: 10m
  path: ./clusters/building-blocks/base/repos/
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: repos
  prune: true
  interval: 10m
  path: ./clusters/building-blocks/base/apps/
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
